-- =============================================
-- Script para insertar datos de prueba en RentGamer
-- Datos extraídos de frontend/src/data/games.js
-- =============================================

-- Primero insertar las categorías
INSERT INTO [dbo].[Categories] ([name], [description])
VALUES 
    ('Acción', 'Juegos de acción llenos de adrenalina y combate intenso'),
    ('Aventura', 'Juegos de aventura con exploración y narrativa cautivadora'),
    ('Estrategia', 'Juegos estratégicos que requieren planificación táctica');

-- Insertar los juegos
INSERT INTO [dbo].[Games] ([name], [category_id], [price], [image], [description], [stock], [is_active])
VALUES
    ('Fuego Mortal', 1, 23.00, '/img-games/action1.png', '"En Fuego Mortal", los jugadores se sumergen en un mundo lleno de peligros y desafíos. Como valientes guerreros, deberán enfrentarse a hordas de enemigos, utilizar armas poderosas y dominar habilidades especiales para salvar al mundo de la destrucción. Con gráficos impresionantes y una jugabilidad intensa, este juego de acción te mantendrá al borde de tu asiento mientras luchas por la supervivencia. ¿Estás listo para enfrentar el fuego mortal?', 10, 1),
    
    ('El Reino Olvidado', 2, 30.00, '/img-games/adventure3.png', 'En "El Reino Olvidado", los jugadores se adentran en un mundo mágico y enigmático lleno de maravillas y peligros. Explora antiguos castillos, bosques encantados y ruinas misteriosas mientras desentrañas los secretos de un reino perdido en el tiempo. En tu viaje, te enfrentarás a desafiantes rompecabezas, criaturas fantásticas y enfrentamientos épicos contra poderosos enemigos. Con gráficos impresionantes y una narrativa cautivadora, "El Reino Olvidado" te sumerge en una aventura llena de magia, exploración y descubrimiento. ¿Estás listo para desvelar los secretos del reino olvidado y convertirte en un verdadero héroe?', 8, 1),
    
    ('Cazadores de Sombras', 1, 32.00, '/img-games/action5.png', 'En "Cazadores de Sombras", los jugadores se convierten en valientes guerreros que se enfrentan a criaturas sobrenaturales que acechan en la oscuridad. Armados con armas místicas y habilidades especiales, tu misión es proteger a la humanidad de las fuerzas del mal. Explora un mundo lleno de misterio y peligro, desentraña antiguos secretos y enfréntate a jefes poderosos en épicas batallas. Con gráficos impresionantes y una jugabilidad emocionante, "Cazadores de Sombras" te sumerge en una aventura llena de acción y fantasía. ¿Estás listo para convertirte en un cazador de sombras y luchar contra las fuerzas de la oscuridad?', 7, 1),
    
    ('Dominio Estratégico', 3, 25.00, '/img-games/strategy1.png', 'En "Dominio Estratégico", los jugadores se convierten en líderes poderosos que buscan expandir su imperio y conquistar nuevas tierras. Tendrás que tomar decisiones estratégicas, gestionar recursos, construir y fortificar tus ciudades, formar alianzas y liderar ejércitos en batallas épicas. El juego ofrece un amplio abanico de opciones tácticas y diplomáticas, permitiéndote elegir entre la diplomacia pacífica o la conquista militar. Con gráficos detallados y una jugabilidad profunda, "Dominio Estratégico" te desafía a demostrar tu habilidad estratégica y convertirte en el gobernante más poderoso. ¿Estás listo para conquistar el mundo y dejar tu huella en la historia?', 6, 1),
    
    ('Infiltración Extrema', 1, 15.00, '/img-games/action3.png', 'En "Infiltración Extrema", los jugadores se convierten en agentes de élite entrenados para llevar a cabo misiones secretas y peligrosas. Tu misión es infiltrarte en instalaciones enemigas altamente fortificadas, evitando las patrullas y los sistemas de seguridad de alta tecnología. "Infiltración Extrema" te sumerge en el mundo del espionaje y la acción encubierta. ¿Estás preparado para el desafío?', 9, 1),
    
    ('Dominio del Reino', 3, 40.00, '/img-games/strategy2.png', 'En "Dominio del Reino", los jugadores asumen el papel de un gobernante astuto y ambicioso que busca expandir su imperio y convertirse en el gobernante supremo. Tendrás que tomar decisiones estratégicas, gestionar recursos, construir y mejorar tus ciudades, formar alianzas y liderar ejércitos en batallas épicas. Desde la diplomacia hasta la guerra, cada movimiento cuenta en tu búsqueda por el dominio total. Con gráficos detallados y una jugabilidad profunda, "Dominio del Reino" te desafía a demostrar tu habilidad estratégica y construir un imperio legendario. ¿Estás listo para gobernar y conquistar el reino?', 5, 1),
    
    ('El Sendero del Destino', 2, 14.00, '/img-games/adventure2.jpg', 'En "El Sendero del Destino", los jugadores se embarcan en un viaje épico a través de tierras místicas y peligrosas en busca de su verdadero destino. Explora vastos y hermosos paisajes, descubre antiguos templos y ruinas, y desentraña los secretos de una antigua profecía. En tu viaje, te enfrentarás a desafiantes acertijos, criaturas mágicas y batallas épicas contra enemigos poderosos. Con gráficos impresionantes y una narrativa envolvente, "El Sendero del Destino" te sumerge en una aventura llena de emoción, misterio y autodescubrimiento. ¿Estás listo para enfrentar tu destino y convertirte en una leyenda?', 8, 1),
    
    ('Destrucción Total', 1, 45.00, '/img-games/action7.jpg', 'En "Destrucción Total", los jugadores se sumergen en un mundo devastado por la guerra y el caos. Eres un soldado de élite que debe luchar contra enemigos implacables y destruir todo a tu paso para restaurar la paz. Utiliza armas de fuego poderosas, explosivos y vehículos de combate para abrirte camino a través de escenarios destructibles y desafiantes. Con gráficos realistas y una jugabilidad intensa, "Destrucción Total" te ofrece una experiencia de acción frenética y llena de adrenalina. ¿Estás preparado para enfrentar la destrucción y convertirte en el héroe que el mundo necesita?', 4, 1),
    
    ('Asalto neotecnológico', 1, 34.00, '/img-games/action9.png', 'En "NeoTech Assault", los jugadores se adentran en un mundo distópico donde las megacorporaciones controlan la sociedad y la tecnología avanzada está en todas partes. Eres parte de un equipo de resistencia que lucha contra el dominio de las corporaciones y busca restaurar la libertad. Utiliza armas de alta tecnología, trajes de combate mejorados y habilidades especiales para enfrentarte a enemigos poderosos y superar desafíos estratégicos. Explora entornos futuristas, hackea sistemas de seguridad y descubre secretos ocultos mientras te abres paso hacia la victoria. Con gráficos asombrosos y una jugabilidad emocionante, "NeoTech Assault" te sumerge en un mundo de acción y rebelión tecnológica. ¿Estás listo para desafiar el poder de las corporaciones y convertirte en el héroe del futuro?', 7, 1),
    
    ('Guerreros Legendarios', 1, 25.00, '/img-games/action2.png', 'En "Guerreros Legendarios", los jugadores se embarcan en una épica aventura en un mundo lleno de magia y peligros. Eres un valiente guerrero elegido para enfrentar a las fuerzas del mal y restaurar el equilibrio en el reino. Lucha contra hordas de enemigos, desbloquea habilidades especiales y reúne poderosos artefactos mientras te abres camino a través de impresionantes paisajes y mazmorras desafiantes. Con gráficos asombrosos y una jugabilidad emocionante, "Guerreros Legendarios" te transporta a un mundo de fantasía lleno de acción y aventura. ¿Estás listo para convertirte en una leyenda?', 10, 1),
    
    ('Velocidad Extrema', 1, 43.00, '/img-games/action6.jpg', 'En "Velocidad Extrema", los jugadores se sumergen en la emoción de las carreras callejeras ilegales. Conduce a toda velocidad por calles urbanas, esquivando el tráfico y desafiando a otros corredores expertos. Personaliza y mejora tu vehículo para obtener el máximo rendimiento y dominar las curvas cerradas y los saltos espectaculares. Compite en una variedad de modos de juego, desde carreras individuales hasta desafíos de tiempo y carreras de eliminación. Con gráficos realistas y una física de conducción precisa, "Velocidad Extrema" te ofrece una experiencia de carreras llena de adrenalina. ¿Estás listo para pisar a fondo el acelerador y convertirte en el rey de la velocidad?', 6, 1),
    
    ('El Legado Perdido', 2, 51.00, '/img-games/adventure4.png', 'En "El Legado Perdido", los jugadores se sumergen en un mundo lleno de misterio y peligro mientras siguen los pasos de sus antepasados en busca de un antiguo legado perdido. Explora exóticos paisajes, descubre tesoros ocultos y resuelve enigmas antiguos mientras te enfrentas a desafíos emocionantes y peligros inesperados. A lo largo de tu viaje, conocerás personajes intrigantes y desvelarás secretos ancestrales que te guiarán hacia tu destino. Con gráficos impresionantes y una narrativa cautivadora, "El Legado Perdido" te sumerge en una aventura épica llena de emoción y descubrimiento. ¿Estás listo para descubrir tu legado y enfrentar los desafíos que te esperan?', 5, 1),
    
    ('Edad de los Imperios', 3, 13.00, '/img-games/strategy3.png', 'En "Edad de los Imperios", los jugadores se sumergen en un mundo histórico lleno de civilizaciones antiguas y batallas épicas. Tendrás el desafío de construir y gestionar tu imperio desde cero, investigar nuevas tecnologías, reclutar y entrenar a tu ejército, y expandir tu dominio a través de la diplomacia o la guerra. Toma decisiones estratégicas cruciales mientras te enfrentas a otros líderes y luchas por la supremacía. Con gráficos impresionantes y una jugabilidad profunda, "Edad de los Imperios" te transporta a una era de conquistas y descubrimientos. ¿Estás listo para forjar tu propio imperio y dejar tu huella en la historia?', 9, 1),
    
    ('El Reino de las Maravillas', 2, 23.00, '/img-games/adventure5.png', 'En "El Reino de las Maravillas", los jugadores se adentran en un mundo mágico y encantado lleno de criaturas fantásticas y paisajes asombrosos. Explora bosques encantados, cuevas misteriosas y ciudades flotantes mientras descubres los secretos de este reino mágico. En tu viaje, te enfrentarás a desafiantes rompecabezas, resolverás acertijos y te encontrarás con personajes únicos que te ayudarán en tu búsqueda. Con gráficos coloridos y una narrativa cautivadora, "El Reino de las Maravillas" te sumerge en una aventura llena de magia, exploración y maravillas inesperadas. ¿Estás listo para sumergirte en este mundo mágico y descubrir los secretos que guarda?', 8, 1),
    
    ('Las crónicas oscuras', 1, 34.00, '/img-games/action10.png', 'Embárcate en una aventura épica como un valiente guerrero que debe enfrentarse a hordas de criaturas oscuras y desentrañar un antiguo misterio. ¿Estás listo para convertirte en una leyenda?.', 7, 1),
    
    ('Ejecutor Implacable', 1, 42.00, '/img-games/action11.png', 'En "Ejecutor Implacable", los jugadores asumen el papel de un agente de élite altamente entrenado que se enfrenta a misiones de alto riesgo en un mundo lleno de peligros. Tu objetivo es eliminar a los criminales más peligrosos y desmantelar organizaciones delictivas mientras te abres camino a través de niveles desafiantes. Utiliza una amplia variedad de armas, tácticas sigilosas y habilidades especiales para enfrentar a tus enemigos y completar tus objetivos. Con gráficos realistas y una jugabilidad intensa, "Ejecutor Implacable" te sumerge en una experiencia de acción implacable. ¿Estás listo para convertirte en el ejecutor más temido?', 6, 1),
    
    ('El Tesoro Perdido', 2, 34.00, '/img-games/adventure1.jpg', 'En "El Tesoro Perdido", los jugadores se embarcan en una emocionante búsqueda en busca de un tesoro legendario oculto en un mundo lleno de misterios y peligros. Explora exuberantes paisajes, ruinas antiguas y cuevas oscuras mientras resuelves acertijos, superas desafíos y enfrentas a enemigos feroces. A lo largo de tu viaje, conocerás a personajes fascinantes y descubrirás secretos ancestrales que te guiarán hacia el tesoro final. Con gráficos impresionantes y una narrativa cautivadora, "El Tesoro Perdido" te sumerge en una aventura épica llena de emoción y descubrimiento. ¿Estás listo para desenterrar el tesoro perdido y convertirte en un verdadero aventurero?', 9, 1),
    
    ('Caos Total', 1, 24.00, '/img-games/action4.png', 'En "Caos Total", los jugadores se adentran en un mundo postapocalíptico donde la sociedad se ha desmoronado y el caos reina. Debes luchar por tu supervivencia en un entorno hostil lleno de pandillas violentas, criaturas mutantes y escasez de recursos. Explora un vasto mapa abierto, mejora tus habilidades de combate y construye alianzas estratégicas para enfrentar los desafíos que se presenten. ¿Estás listo para enfrentar el caos y reclamar tu lugar en este nuevo mundo?', 7, 1),
    
    ('Vanguardia cibernética', 1, 13.00, '/img-games/action8.png', 'En "Cyber Vanguard", los jugadores se sumergen en un mundo futurista donde la tecnología ha avanzado a niveles extraordinarios. Eres un agente de élite equipado con implantes cibernéticos y armamento de vanguardia. Tu misión es enfrentarte a corporaciones corruptas y grupos rebeldes mientras desentrañas una conspiración que amenaza con sumir al mundo en el caos. Utiliza tus habilidades mejoradas, combate cuerpo a cuerpo y armas futuristas para superar desafíos y desbloquear nuevos poderes. Con gráficos de última generación y una jugabilidad frenética, "Cyber Vanguard" te transporta a un futuro distópico lleno de acción y tecnología avanzada. ¿Estás listo para convertirte en el protector de la humanidad en el mundo cibernético?', 8, 1),
    
    ('Invasión Total', 1, 24.00, '/img-games/action12.png', 'En "Invasión Total", los jugadores se enfrentan a una amenaza extraterrestre que ha invadido la Tierra. Eres parte de un equipo especializado en la lucha contra los invasores y tu misión es repeler la invasión y salvar a la humanidad. Utiliza armas futuristas, vehículos de combate y habilidades especiales para enfrentarte a las hordas alienígenas en batallas épicas. Explora entornos devastados, descubre secretos ocultos y libera a ciudades tomadas por los invasores. Con gráficos impresionantes y una jugabilidad emocionante, "Invasión Total" te sumerge en una lucha desesperada por la supervivencia de la humanidad. ¿Estás listo para enfrentar la invasión y convertirte en el héroe que la Tierra necesita?', 6, 1),
    
    ('El Laberinto Estratégico', 3, 34.00, '/img-games/strategy4.png', 'En "El Laberinto Estratégico", los jugadores se enfrentan a desafiantes laberintos llenos de trampas mortales y enemigos astutos. Tu objetivo es encontrar la salida del laberinto mientras te enfrentas a obstáculos estratégicos y tomas decisiones tácticas para superar cada nivel. Utiliza tu ingenio y planifica cuidadosamente tus movimientos para evitar trampas y derrotar a los enemigos en tu camino. Con gráficos intrigantes y una jugabilidad estratégica, "El Laberinto Estratégico" te desafía a demostrar tus habilidades de resolución de problemas y estrategia. ¿Estás preparado para adentrarte en el laberinto y encontrar la salida?', 5, 1);

PRINT '✅ Datos de prueba insertados correctamente';
PRINT 'Total: 3 categorías + 21 juegos';
